help:
	@echo "Makefile Targets:"
	@echo ""
	@echo "database      : Builds the database and imports the initial set of data"
	@echo "doc           : Generates the documentation"
	@echo "test          : Run unit testing suite"
	@echo "runserver     : Runs a local instance of the project"
	@echo "clean         : cleans the project directory"
	@echo "binclean      : cleans compiled python files"
	@echo "docclean      : Clears generated Documentation"
	@echo "databaseclean : Cleans up the database"

doc:
	cd ../design/pydoc && python ../../implementation/manage.py makedoc
	@echo ""
	@echo "################################################"
	@echo "Documentation written to design/pydoc directory"
	@echo "Note that this is not the documentation module that you see here"
	@echo "cd ../design/pydoc"
	@echo "################################################"

runserver:
	@echo "running Django server in current directory"
	python manage.py runserver

syncdb: database

database:
	python ./manage.py syncdb --noinput
	@echo "################################################"
	@echo "Note: this does not clear the database or update changed objects"
	@echo "Unless you run 'make cleandatabase' first"
	@echo "################################################"

test:
	@echo "Running tests"
	python ./manage.py test

	
clean: binclean docclean databaseclean
	@echo ""
	@echo "################################################"
	@echo "Precompiled python files, autogenerated documentation"
	@echo "and the database file has been removed"
	@echo "################################################"

cleanbin: binclean
binclean:
	find . -iname '*.pyc' -exec rm {} \;

cleandoc: docclean
docclean:
	find ../design/pydoc -iname '*.html' \
		-not -name '*chat.html' \
		-not -name '*index.html' \
		-delete

cleandatabase: databaseclean
databaseclean:
	rm -f *.sqlite3
