all:

doc:
	@echo "Currently unsupported.  Implementation deadline Milestone3"

runserver:
	@echo "running Django server in current directory"
	python manage.py runserver
	
clean:
	find . -iname '*.pyc' -exec rm {} \;
